version: "3"
services:
  # zookeeper:
  #   image: 'bitnami/zookeeper:latest'
  #   ports:
  #     - '2181:2181'
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes

  # kafka:
  #   restart: always
  #   image: 'bitnami/kafka:latest'
  #   container_name: 'kafka'
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  #     - KAFKA_ADVERTISED_LISTENERS=LISTENER_BOB://kafka:9092
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     # KAFKA_ADVERTISED_HOST_NAME: <KAFKA_CONTAINER_IP_ADDRESS>
  #     # ZOOKEEPER_IP: <ZOOKEEPER_CONTAINER_IP_ADDRESS>
  #     # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     # ALLOW_PLAINTEXT_LISTENER: 1
  #   depends_on:
  #     - zookeeper


  kafka:
    ports:
      - 9092:9092
      - 29094:29092
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://127.0.0.1:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1   
    networks:
      - kafka
    depends_on:
      - zookeeper

  zookeeper:
    ports:
      - 32181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka

  web:
    image: node-server:1.0.0
    build: .
    command: npm start
    volumes:
      - ./:/code
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    networks:
      - kafka

networks:
  kafka:
    external: false